#!/bin/bash
# coauthor bootstrap. Runs once, as root, at first boot.
#
# NOTE: this file is rendered by Terraform's templatefile(). Terraform consumes
# $${...}, so every *shell* variable below is written $${VAR} and every
# *Terraform* variable is written $${...} with no extra dollar. Getting this
# wrong produces a script that silently expands to empty strings.
set -euxo pipefail
exec > >(tee /var/log/coauthor-bootstrap.log) 2>&1

export DEBIAN_FRONTEND=noninteractive

timedatectl set-timezone "${timezone}"

apt-get update
apt-get -y upgrade
apt-get -y install \
  python3-venv python3-pip \
  xvfb x11vnc \
  fonts-liberation fonts-noto-color-emoji \
  unattended-upgrades curl unzip debian-keyring debian-archive-keyring \
  apt-transport-https ca-certificates gnupg sqlite3

# ---------------------------------------------------------------------------
# AWS CLI v2, from Amazon directly.
#
# Ubuntu 24.04 has no 'awscli' package at all -- it was dropped from noble, and
# apt reports "Candidate: (none)" even with universe enabled. Amazon's own
# installer is the supported route and does not depend on distro packaging.
# ---------------------------------------------------------------------------
if ! command -v aws >/dev/null; then
  ARCH="$(uname -m)"          # aarch64 on Graviton, x86_64 otherwise
  curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-$${ARCH}.zip" -o /tmp/awscliv2.zip
  unzip -q /tmp/awscliv2.zip -d /tmp
  /tmp/aws/install
  rm -rf /tmp/aws /tmp/awscliv2.zip
fi
aws --version

# ---------------------------------------------------------------------------
# Swap. Cheap insurance against a Chromium memory spike on a 2 GB box.
# ---------------------------------------------------------------------------
if [ ! -f /swapfile ]; then
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

# ---------------------------------------------------------------------------
# Caddy -- terminates TLS, gets the Let's Encrypt certificate, proxies to the
# dashboard on localhost. Installed from Caddy's own apt repository.
# ---------------------------------------------------------------------------
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
  | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
  | tee /etc/apt/sources.list.d/caddy-stable.list
apt-get update
apt-get -y install caddy

# ---------------------------------------------------------------------------
# Application user. No login shell password, no sudo.
# ---------------------------------------------------------------------------
id -u coauthor &>/dev/null || useradd -m -d /opt/coauthor -s /bin/bash coauthor
mkdir -p /opt/coauthor/app
chown -R coauthor:coauthor /opt/coauthor

# ---------------------------------------------------------------------------
# Secrets. Generated randomly here so the box is never briefly protected by a
# guessable password. Read them back with:
#     sudo cat /etc/coauthor.env
# ---------------------------------------------------------------------------
#
# openssl rather than `tr </dev/urandom | head -c N`: head exits the moment it
# has its bytes, tr takes SIGPIPE and returns 141, pipefail promotes that to the
# pipeline's status, and set -e kills the whole bootstrap. Whether it fires is a
# race, so the pattern half-works and fails at a different line each boot.
if [ ! -f /etc/coauthor.env ]; then
  GEN_PW="$(openssl rand -hex 7)"
  GEN_SECRET="$(openssl rand -hex 32)"
  cat > /etc/coauthor.env <<ENVEOF
# Shared password for the dashboard. Change it to whatever you like, then:
#   sudo systemctl restart coauthor-web
COAUTHOR_PASSWORD=$${GEN_PW}
# Signs session cookies. Changing it logs everyone out. Keep it secret.
COAUTHOR_SECRET=$${GEN_SECRET}
ENVEOF
  chmod 600 /etc/coauthor.env
  chown root:root /etc/coauthor.env
fi

# ---------------------------------------------------------------------------
# Caddyfile is generated at runtime because it needs the public IP, which is
# not known at template time -- the Elastic IP is associated after launch.
# ---------------------------------------------------------------------------
cat > /usr/local/bin/coauthor-caddy-config <<'CADDYGEN'
#!/bin/bash
set -euo pipefail
TOKEN=$(curl -sS -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 60")
IP=$(curl -sS -H "X-aws-ec2-metadata-token: $TOKEN" \
  http://169.254.169.254/latest/meta-data/public-ipv4)
HOST="coauthor.$${IP//./-}.sslip.io"

cat > /etc/caddy/Caddyfile <<EOF
# Generated by coauthor-caddy-config. Edits here are overwritten on deploy.
$HOST {
	encode zstd gzip

	# The dashboard is behind a password, but there is no reason for any of it
	# to be indexed, framed or sniffed.
	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains"
		X-Content-Type-Options    "nosniff"
		X-Frame-Options           "DENY"
		Referrer-Policy           "no-referrer"
		-Server
	}

	reverse_proxy 127.0.0.1:8000
}

# Anything reaching this host by raw IP or another name gets nothing useful.
:80 {
	respond "coauthor" 200
}
EOF

echo "$HOST" > /etc/coauthor.hostname
caddy fmt --overwrite /etc/caddy/Caddyfile
# Deliberately does NOT reload caddy. This script runs from a unit ordered
# Before=caddy.service, so asking systemd to act on caddy from in here makes
# the two units wait on each other and hangs the whole boot. Callers that need
# a reload (coauthor-deploy) do it themselves, outside the boot transaction.
echo "dashboard hostname: $HOST"
CADDYGEN
chmod 755 /usr/local/bin/coauthor-caddy-config

# ---------------------------------------------------------------------------
# Deploy helper. Pulls the tarball this bucket receives and restarts services.
#     sudo coauthor-deploy
# ---------------------------------------------------------------------------
cat > /usr/local/bin/coauthor-deploy <<'DEPLOYEOF'
#!/bin/bash
set -euo pipefail
BUCKET="__DEPLOY_BUCKET__"
APP=/opt/coauthor/app

echo "==> fetching s3://$BUCKET/app.tar.gz"
aws s3 cp "s3://$BUCKET/app.tar.gz" /tmp/app.tar.gz

echo "==> unpacking (data and credentials are preserved)"
install -d -o coauthor -g coauthor "$APP"
tar xzf /tmp/app.tar.gz -C "$APP"
chown -R coauthor:coauthor /opt/coauthor

echo "==> python dependencies"
sudo -u coauthor bash -lc "
  test -d /opt/coauthor/venv || python3 -m venv /opt/coauthor/venv
  /opt/coauthor/venv/bin/pip install --quiet --upgrade pip
  /opt/coauthor/venv/bin/pip install --quiet -r $APP/requirements.txt
  /opt/coauthor/venv/bin/python -m playwright install chromium
"
/opt/coauthor/venv/bin/python -m playwright install-deps chromium

echo "==> tls hostname"
/usr/local/bin/coauthor-caddy-config
systemctl reload caddy || systemctl restart caddy

echo "==> restarting"
systemctl daemon-reload
systemctl restart coauthor-web
systemctl restart coauthor-watcher || true
systemctl start coauthor-poll.timer

sleep 3
# `| head` would SIGPIPE systemctl and, under pipefail, fail the deploy for no
# reason; systemctl also exits non-zero whenever a listed unit is not running.
systemctl --no-pager --lines=0 --no-legend status coauthor-web coauthor-watcher || true
echo
echo "dashboard: https://$(cat /etc/coauthor.hostname)"
echo "password:  $(grep COAUTHOR_PASSWORD /etc/coauthor.env | cut -d= -f2)"
DEPLOYEOF
sed -i "s|__DEPLOY_BUCKET__|${deploy_bucket}|" /usr/local/bin/coauthor-deploy
chmod 755 /usr/local/bin/coauthor-deploy

# ---------------------------------------------------------------------------
# systemd units
# ---------------------------------------------------------------------------

# The dashboard. Binds to localhost only; Caddy is the only thing that reaches it.
cat > /etc/systemd/system/coauthor-web.service <<'UNITEOF'
[Unit]
Description=coauthor dashboard
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=coauthor
WorkingDirectory=/opt/coauthor/app
EnvironmentFile=/etc/coauthor.env
ExecStart=/opt/coauthor/venv/bin/uvicorn server:app --host 127.0.0.1 --port 8000
Restart=always
RestartSec=10
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target
UNITEOF

# The presence watcher. xvfb-run keeps Chromium headful on a headless box,
# which is what Google's sign-in handling expects.
cat > /etc/systemd/system/coauthor-watcher.service <<'UNITEOF'
[Unit]
Description=coauthor presence watcher
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=coauthor
WorkingDirectory=/opt/coauthor/app
ExecStart=/usr/bin/xvfb-run -a --server-args="-screen 0 1680x1000x24" \
          /opt/coauthor/venv/bin/python /opt/coauthor/app/presence_watcher.py
Restart=always
RestartSec=30
# Exit 2 (signed out) and 3 (no access to the document) both need a person to
# act -- one to sign in over VNC, the other to share the document. Retrying is
# useless for those: a signed-out session was once relaunched 696 times in a
# row, burning CPU and burying the real message in the journal. Crashes and
# hangs still restart normally.
RestartPreventExitStatus=2 3
# Chromium leaks over long runs; a nightly restart is cheaper than debugging it.
RuntimeMaxSec=86400

[Install]
WantedBy=multi-user.target
UNITEOF

# The poller runs as a timer rather than a loop, so a crash cannot wedge it.
cat > /etc/systemd/system/coauthor-poll.service <<'UNITEOF'
[Unit]
Description=coauthor activity poll (single pass)

[Service]
Type=oneshot
User=coauthor
WorkingDirectory=/opt/coauthor/app
ExecStart=/opt/coauthor/venv/bin/python /opt/coauthor/app/activity_poller.py --once
UNITEOF

cat > /etc/systemd/system/coauthor-poll.timer <<'UNITEOF'
[Unit]
Description=coauthor activity poll every 5 minutes

[Timer]
OnBootSec=2min
OnUnitActiveSec=5min
Persistent=true

[Install]
WantedBy=timers.target
UNITEOF

# Regenerate the TLS hostname on every boot, in case the address ever changes.
cat > /etc/systemd/system/coauthor-caddy-config.service <<'UNITEOF'
[Unit]
Description=coauthor: write Caddyfile for the current public IP
After=network-online.target
Wants=network-online.target
Before=caddy.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/coauthor-caddy-config
RemainAfterExit=true

[Install]
WantedBy=multi-user.target
UNITEOF

systemctl daemon-reload
systemctl enable coauthor-caddy-config.service
systemctl enable coauthor-web.service coauthor-watcher.service
systemctl enable coauthor-poll.timer

# Run the generator directly rather than via `systemctl start`. This script is
# executing inside cloud-final.service, so a blocking `systemctl start` waits
# for a job that systemd will not schedule until cloud-final finishes -- which
# is the deadlock that hung the first build. Calling the script needs no
# systemd transaction at all, and --no-block keeps the caddy restart clear of
# the same trap. Services stay down until code is deployed; they retry.
/usr/local/bin/coauthor-caddy-config || true
systemctl restart --no-block caddy || true

# Sentinel, so a deploy can tell "bootstrap still running" apart from
# "bootstrap died halfway". set -e means a failure anywhere above skips this.
date -Is > /etc/coauthor.bootstrapped

echo "BOOTSTRAP COMPLETE -- run 'sudo coauthor-deploy' after uploading the app"
